export const PATH_DASHBOARD = "/"
export const PATH_AHORROS = "/ahorros"
export const PATH_CREDITOS = "/creditos"
export const PATH_INTERES_SOCIOS = "/interesSocios"
export const PATH_APORTE_SOCIOS = "/aporteSocios"
